import { ArchetypeDefinition, ArchetypeId } from '../types/book';

export const ARCHETYPES: Record<ArchetypeId, ArchetypeDefinition> = {
  'speed-reader': {
    id: 'speed-reader',
    name: 'Speed Reader / Page Turner',
    shortName: 'Speed Reader',
    tagline: 'Blink and you miss it! A force of nature through plotlines.',
    ppdRange: '80+ PPD',
    minPpd: 80,
    maxPpd: Infinity,
    description:
      'You devour narratives at supersonic velocity. Plot twists don’t have time to gather dust, and thick tomes are mere weekend sprints.',
    celebrationPhilosophy:
      'Celebrates unstoppable curiosity, rapid cognitive immersion, and the electric thrill of binge-reading without pause.',
    themeColor: 'amber',
    accentHex: '#f59e0b',
    glowHex: 'rgba(245, 158, 11, 0.25)',
    bgGradient: 'from-amber-500/20 via-orange-500/10 to-transparent',
    badgeEmoji: '⚡',
    iconName: 'Zap',
    strengths: ['Hypersonic pacing', 'Plot momentum devourer', 'Zero cliffhanger lag'],
  },
  'steady-cruiser': {
    id: 'steady-cruiser',
    name: 'Steady Cruiser',
    shortName: 'Steady Cruiser',
    tagline: 'Consistent, reliable, and smooth execution.',
    ppdRange: '40–79 PPD',
    minPpd: 40,
    maxPpd: 79.99,
    description:
      'The gold standard of literary endurance. You show up with rhythmic momentum, carving out dedicated daily reading windows like clockwork.',
    celebrationPhilosophy:
      'Celebrates ironclad habit formation, balanced lifestyle integration, and disciplined progress that conquers whole bookshelves.',
    themeColor: 'emerald',
    accentHex: '#10b981',
    glowHex: 'rgba(16, 185, 129, 0.25)',
    bgGradient: 'from-emerald-500/20 via-teal-500/10 to-transparent',
    badgeEmoji: '🧭',
    iconName: 'Compass',
    strengths: ['Unshakable consistency', 'Smooth daily cadence', 'Habit mastery'],
  },
  'book-sommelier': {
    id: 'book-sommelier',
    name: 'Book Sommelier',
    shortName: 'Book Sommelier',
    tagline: 'Savoring every word, chapter, and plot nuance.',
    ppdRange: '15–39 PPD',
    minPpd: 15,
    maxPpd: 39.99,
    description:
      'You don’t rush a masterpiece. You let exquisite prose aerate, highlight striking metaphors, and let character motivations steep like fine vintage wine.',
    celebrationPhilosophy:
      'Celebrates deep textual absorption, sensory richness, intellectual nuance, and profound literary appreciation over mere speed.',
    themeColor: 'purple',
    accentHex: '#a855f7',
    glowHex: 'rgba(168, 85, 247, 0.25)',
    bgGradient: 'from-purple-500/20 via-fuchsia-500/10 to-transparent',
    badgeEmoji: '🍷',
    iconName: 'Wine',
    strengths: ['Prose aeration', 'Subtext appreciation', 'Deep character intimacy'],
  },
  'bedtime-taster': {
    id: 'bedtime-taster',
    name: 'Bedtime Taster',
    shortName: 'Bedtime Taster',
    tagline: 'Gentle, low-pressure reading to unwind.',
    ppdRange: '< 15 PPD',
    minPpd: 0,
    maxPpd: 14.99,
    description:
      'Reading as sacred, restorative self-care. Just a tranquil chapter or two under warm lamplight to calm the nervous system before drifting into dreams.',
    celebrationPhilosophy:
      'Celebrates gentle mindful boundaries, zero-pressure pleasure, stress relief, and honoring reading as peaceful sanctuary.',
    themeColor: 'sky',
    accentHex: '#38bdf8',
    glowHex: 'rgba(56, 189, 248, 0.25)',
    bgGradient: 'from-sky-500/20 via-indigo-500/10 to-transparent',
    badgeEmoji: '🌙',
    iconName: 'Moon',
    strengths: ['Mindful unwinding', 'Zero-anxiety leisure', 'Restorative ritual'],
  },
};

export const INITIAL_SAMPLE_BOOKS: any[] = [
  {
    id: 'sample-1',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    totalPages: 496,
    startDate: '2026-09-28',
    finishDate: '2026-10-01',
    elapsedDays: 4,
    ppd: 124,
    archetypeId: 'speed-reader',
    rating: 4.8,
    review:
      'A triumph of scientific optimism and friendship! Once Rocky entered the scene, sleep was simply not an option.',
    genre: 'Sci-Fi / Adventure',
    format: 'Physical',
    coverUrl: 'https://covers.openlibrary.org/b/id/11107872-M.jpg',
    isbn: '9780593135204',
    publisher: 'Ballantine Books',
    celebrationMessage:
      'Rocket propulsion engaged! Tearing through 124 pages a day on "Project Hail Mary" proves that when the stakes are planetary, your reading speed goes interstellar. An absolute Page Turner tour-de-force!',
    createdAt: Date.now() - 500000,
  },
  {
    id: 'sample-2',
    title: 'Tomorrow, and Tomorrow, and Tomorrow',
    author: 'Gabrielle Zevin',
    totalPages: 416,
    startDate: '2026-09-20',
    finishDate: '2026-09-27',
    elapsedDays: 8,
    ppd: 52,
    archetypeId: 'steady-cruiser',
    rating: 4.4,
    review:
      'A gorgeous exploration of collaborative art, friendship, video games, and grief over decades. Such a steady, fulfilling rhythm.',
    genre: 'Literary Fiction',
    format: 'E-Reader',
    coverUrl: 'https://covers.openlibrary.org/b/id/12749457-M.jpg',
    isbn: '9780593321201',
    publisher: 'Knopf',
    celebrationMessage:
      'Clockwork precision meets emotional depth! Gliding through 52 pages a day over 8 days is the mark of a master Steady Cruiser. You gave Sam and Sadie room to breathe while keeping unbeatable daily momentum.',
    createdAt: Date.now() - 400000,
  },
  {
    id: 'sample-3',
    title: 'A Gentleman in Moscow',
    author: 'Amor Towles',
    totalPages: 462,
    startDate: '2026-09-05',
    finishDate: '2026-09-22',
    elapsedDays: 18,
    ppd: 25.7,
    archetypeId: 'book-sommelier',
    rating: 4.6,
    review:
      'Count Rostov’s wit and elegance in the Hotel Metropol made every paragraph worth lingering over. Unrushed, luxurious storytelling.',
    genre: 'Historical Fiction',
    format: 'Physical',
    coverUrl: 'https://covers.openlibrary.org/b/id/8315182-M.jpg',
    isbn: '9780735221079',
    publisher: 'Viking',
    celebrationMessage:
      'An exquisite literary vintage! At 25.7 pages a day across 18 days, you honored Amor Towles’ prose with true Sommelier patience. Great literature is never a race—it is a conversation across time.',
    createdAt: Date.now() - 300000,
  },
  {
    id: 'sample-4',
    title: 'Before the Coffee Gets Cold',
    author: 'Toshikazu Kawaguchi',
    totalPages: 224,
    startDate: '2026-09-01',
    finishDate: '2026-09-20',
    elapsedDays: 20,
    ppd: 11.2,
    archetypeId: 'bedtime-taster',
    rating: 4.2,
    review:
      'Read 10-15 pages each night with a cup of chamomile tea. Melancholy yet deeply comforting café time travel.',
    genre: 'Cozy Magical Realism',
    format: 'Physical',
    coverUrl: 'https://covers.openlibrary.org/b/id/10189912-M.jpg',
    isbn: '9781335430991',
    publisher: 'Hanover Square Press',
    celebrationMessage:
      'Sanctuary achieved. Gently tasting 11.2 pages a night across 20 evenings is the gold standard of restorative reading. You chose peace over speed, turning this book into a nightly cup of comfort.',
    createdAt: Date.now() - 200000,
  },
];
