import { ArchetypeDefinition, ArchetypeId, BookEntry } from '../types/book';

export const ARCHETYPES: Record<ArchetypeId, ArchetypeDefinition> = {
  'bedtime-taster': {
    id: 'bedtime-taster',
    name: 'Bedtime Taster',
    shortName: 'Bedtime Taster',
    tagline: 'Gentle, low-pressure reading to unwind.',
    ppdRange: '0.1 – 14.9 PPD',
    minPpd: 0.1,
    maxPpd: 14.99,
    description:
      'Reading as sacred, restorative self-care. Just a tranquil chapter or two under warm lamplight to calm the nervous system before drifting into dreams.',
    celebrationPhilosophy:
      'Celebrates gentle mindful boundaries, zero-pressure pleasure, stress relief, and honoring reading as a peaceful sanctuary.',
    themeColor: 'violet',
    accentHex: '#8b5cf6',
    glowHex: 'rgba(139, 92, 246, 0.3)',
    bgGradient: 'from-violet-500/20 via-purple-500/10 to-transparent',
    badgeEmoji: '🌙',
    iconName: 'Moon',
    strengths: ['Mindful unwinding', 'Zero-anxiety leisure', 'Restorative ritual'],
  },
  'book-sommelier': {
    id: 'book-sommelier',
    name: 'Book Sommelier',
    shortName: 'Book Sommelier',
    tagline: 'Savoring every word, chapter, and plot nuance.',
    ppdRange: '15.0 – 29.9 PPD',
    minPpd: 15.0,
    maxPpd: 29.99,
    description:
      'You don’t rush a masterpiece. You let exquisite prose aerate, highlight striking metaphors, and let character motivations steep like fine vintage wine.',
    celebrationPhilosophy:
      'Celebrates deep textual absorption, sensory richness, intellectual nuance, and profound literary appreciation over mere speed.',
    themeColor: 'pink',
    accentHex: '#ec4899',
    glowHex: 'rgba(236, 72, 153, 0.3)',
    bgGradient: 'from-pink-500/20 via-rose-500/10 to-transparent',
    badgeEmoji: '🍷',
    iconName: 'Wine',
    strengths: ['Prose aeration', 'Subtext appreciation', 'Deep character intimacy'],
  },
  'cozy-lounge-reader': {
    id: 'cozy-lounge-reader',
    name: 'Cozy Lounge Reader',
    shortName: 'Cozy Lounge Reader',
    tagline: 'Settled in for the long haul; effortless immersion.',
    ppdRange: '30.0 – 44.9 PPD',
    minPpd: 30.0,
    maxPpd: 44.99,
    description:
      'Blanket wrapped, warm beverage in hand, completely immersed in another world. You read comfortably without rushing, letting the narrative swallow your afternoon.',
    celebrationPhilosophy:
      'Celebrates deep comfort, sustained attention span, escape from daily noise, and cozy narrative indulgence.',
    themeColor: 'blue',
    accentHex: '#3b82f6',
    glowHex: 'rgba(59, 130, 246, 0.3)',
    bgGradient: 'from-blue-500/20 via-sky-500/10 to-transparent',
    badgeEmoji: '🛋️',
    iconName: 'Armchair',
    strengths: ['Effortless immersion', 'Sustained focus', 'Atmospheric reading'],
  },
  'steady-cruiser': {
    id: 'steady-cruiser',
    name: 'Steady Cruiser',
    shortName: 'Steady Cruiser',
    tagline: 'Consistent, reliable, and smooth execution.',
    ppdRange: '45.0 – 64.9 PPD',
    minPpd: 45.0,
    maxPpd: 64.99,
    description:
      'The gold standard of literary endurance. You show up with rhythmic momentum, carving out dedicated daily reading windows like clockwork.',
    celebrationPhilosophy:
      'Celebrates ironclad habit formation, balanced lifestyle integration, and disciplined progress that conquers whole bookshelves.',
    themeColor: 'cyan',
    accentHex: '#06b6d4',
    glowHex: 'rgba(6, 182, 212, 0.3)',
    bgGradient: 'from-cyan-500/20 via-teal-500/10 to-transparent',
    badgeEmoji: '🧭',
    iconName: 'Compass',
    strengths: ['Unshakable consistency', 'Smooth daily cadence', 'Habit mastery'],
  },
  'momentum-builder': {
    id: 'momentum-builder',
    name: 'Momentum Builder',
    shortName: 'Momentum Builder',
    tagline: 'Gaining speed as the climax approaches.',
    ppdRange: '65.0 – 89.9 PPD',
    minPpd: 65.0,
    maxPpd: 89.99,
    description:
      'Started steady, but the stakes just got real! When the story heats up, your reading speed accelerates with irresistible magnetic force toward the finale.',
    celebrationPhilosophy:
      'Celebrates narrative acceleration, emotional investment, crescendo pacing, and dynamic chapter compounding.',
    themeColor: 'emerald',
    accentHex: '#10b981',
    glowHex: 'rgba(16, 185, 129, 0.3)',
    bgGradient: 'from-emerald-500/20 via-teal-500/10 to-transparent',
    badgeEmoji: '🚀',
    iconName: 'Rocket',
    strengths: ['Dynamic acceleration', 'Crescendo reading', 'Climax devourer'],
  },
  'speed-reader': {
    id: 'speed-reader',
    name: 'Speed Reader',
    shortName: 'Speed Reader',
    tagline: 'Blink and you miss it! A force of nature through plotlines.',
    ppdRange: '90.0 – 124.9 PPD',
    minPpd: 90.0,
    maxPpd: 124.99,
    description:
      'You devour narratives at supersonic velocity. Plot twists don’t have time to gather dust, and thick tomes are mere weekend sprints.',
    celebrationPhilosophy:
      'Celebrates unstoppable curiosity, rapid cognitive immersion, and the electric thrill of binge-reading without pause.',
    themeColor: 'amber',
    accentHex: '#f59e0b',
    glowHex: 'rgba(245, 158, 11, 0.3)',
    bgGradient: 'from-amber-500/20 via-orange-500/10 to-transparent',
    badgeEmoji: '⚡',
    iconName: 'Zap',
    strengths: ['Hypersonic pacing', 'Plot momentum devourer', 'Zero cliffhanger lag'],
  },
  'narrative-comet': {
    id: 'narrative-comet',
    name: 'Narrative Comet',
    shortName: 'Narrative Comet',
    tagline: 'An unstoppable literary streak blazing through entire series.',
    ppdRange: '125.0+ PPD',
    minPpd: 125.0,
    maxPpd: Infinity,
    description:
      'Literary supernova velocity! You tear through multi-hundred-page epic novels in a single blazing streak. You don’t read books—you orbit them at light speed.',
    celebrationPhilosophy:
      'Celebrates transcendent reading stamina, cosmic story absorption, boundary-shattering velocity, and ferocious literary passion.',
    themeColor: 'rose',
    accentHex: '#f43f5e',
    glowHex: 'rgba(244, 63, 94, 0.3)',
    bgGradient: 'from-rose-500/20 via-pink-500/10 to-transparent',
    badgeEmoji: '💥',
    iconName: 'Flame',
    strengths: ['Cosmic velocity', 'Multi-volume marathoner', 'Pure reading fervor'],
  },
};

export const INITIAL_SAMPLE_BOOKS: BookEntry[] = [
  {
    id: 'sample-0',
    title: 'Red Rising',
    author: 'Pierce Brown',
    totalPages: 382,
    startDate: '2026-10-02',
    finishDate: '2026-10-03',
    elapsedDays: 2,
    ppd: 191,
    archetypeId: 'narrative-comet',
    rating: 4.9,
    review:
      'Unstoppable velocity! Started on a Friday evening and couldn’t put it down until the final page. High-octane sci-fi brilliance.',
    genre: 'Science Fiction',
    format: 'Physical',
    coverUrl: 'https://covers.openlibrary.org/b/id/8389658-M.jpg',
    isbn: '9780345539786',
    publisher: 'Del Rey',
    celebrationMessage:
      'Supernova velocity unleashed! Burning through 191 pages a day on "Red Rising" in 2 days proves you were possessed by pure literary fervor. You didn’t just read this book—you orbited it at cosmic speed like a true Narrative Comet!',
    createdAt: Date.now() - 600000,
  },
  {
    id: 'sample-1',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    totalPages: 496,
    startDate: '2026-09-28',
    finishDate: '2026-10-01',
    elapsedDays: 4,
    ppd: 124,
    archetypeId: 'speed-reader',
    rating: 4.8,
    review:
      'A triumph of scientific optimism and friendship! Once Rocky entered the scene, sleep was simply not an option.',
    genre: 'Science Fiction',
    format: 'Physical',
    coverUrl: 'https://covers.openlibrary.org/b/id/11107872-M.jpg',
    isbn: '9780593135204',
    publisher: 'Ballantine Books',
    celebrationMessage:
      'Rocket propulsion engaged! Tearing through 124 pages a day on "Project Hail Mary" proves that when the stakes are planetary, your reading speed goes supersonic. A true Speed Reader tour-de-force!',
    createdAt: Date.now() - 500000,
  },
  {
    id: 'sample-1b',
    title: 'The Seven Husbands of Evelyn Hugo',
    author: 'Taylor Jenkins Reid',
    totalPages: 400,
    startDate: '2026-09-23',
    finishDate: '2026-09-27',
    elapsedDays: 5,
    ppd: 80,
    archetypeId: 'momentum-builder',
    rating: 4.7,
    review:
      'Gained serious speed with every new husband! The climax was totally engrossing and left me breathless.',
    genre: 'Historical Fiction',
    format: 'Physical',
    coverUrl: 'https://covers.openlibrary.org/b/id/8431180-M.jpg',
    isbn: '9781501161933',
    publisher: 'Atria Books',
    celebrationMessage:
      'Dynamic momentum in action! Reading 80 pages per day across 5 days shows your pace accelerated as the stakes intensified. You closed this book with magnetic finale energy as a Momentum Builder!',
    createdAt: Date.now() - 450000,
  },
  {
    id: 'sample-2',
    title: 'Tomorrow, and Tomorrow, and Tomorrow',
    author: 'Gabrielle Zevin',
    totalPages: 416,
    startDate: '2026-09-20',
    finishDate: '2026-09-27',
    elapsedDays: 8,
    ppd: 52,
    archetypeId: 'steady-cruiser',
    rating: 4.4,
    review:
      'A gorgeous exploration of collaborative art, friendship, video games, and grief over decades. Such a steady, fulfilling rhythm.',
    genre: 'Literary Fiction',
    format: 'E-Reader',
    coverUrl: 'https://covers.openlibrary.org/b/id/12749457-M.jpg',
    isbn: '9780593321201',
    publisher: 'Knopf',
    celebrationMessage:
      'Clockwork precision meets emotional depth! Gliding through 52 pages a day over 8 days is the mark of a master Steady Cruiser. You gave Sam and Sadie room to breathe while keeping unbeatable daily momentum.',
    createdAt: Date.now() - 400000,
  },
  {
    id: 'sample-2b',
    title: 'Legends & Lattes',
    author: 'Travis Baldree',
    totalPages: 300,
    startDate: '2026-09-12',
    finishDate: '2026-09-19',
    elapsedDays: 8,
    ppd: 37.5,
    archetypeId: 'cozy-lounge-reader',
    rating: 4.5,
    review:
      'The coziest high-fantasy book ever written. Hot coffee, cinnamon rolls, and zero high-stress battles. Absolute perfection.',
    genre: 'Fantasy',
    format: 'Physical',
    coverUrl: 'https://covers.openlibrary.org/b/id/12836263-M.jpg',
    isbn: '9781250886088',
    publisher: 'Tor Books',
    celebrationMessage:
      'Effortless immersion achieved! Curling up with "Legends & Lattes" at a comforting 37.5 pages a day over 8 days is pure reader bliss. Zero deadlines, total immersion—a true Cozy Lounge Reader paradise!',
    createdAt: Date.now() - 350000,
  },
  {
    id: 'sample-3',
    title: 'A Gentleman in Moscow',
    author: 'Amor Towles',
    totalPages: 462,
    startDate: '2026-09-05',
    finishDate: '2026-09-22',
    elapsedDays: 18,
    ppd: 25.7,
    archetypeId: 'book-sommelier',
    rating: 4.6,
    review:
      'Count Rostov’s wit and elegance in the Hotel Metropol made every paragraph worth lingering over. Unrushed, luxurious storytelling.',
    genre: 'Historical Fiction',
    format: 'Physical',
    coverUrl: 'https://covers.openlibrary.org/b/id/8315182-M.jpg',
    isbn: '9780735221079',
    publisher: 'Viking',
    celebrationMessage:
      'An exquisite literary vintage! At 25.7 pages a day across 18 days, you honored Amor Towles’ prose with true Sommelier patience. Great literature is never a race—it is a conversation across time.',
    createdAt: Date.now() - 300000,
  },
  {
    id: 'sample-4',
    title: 'Before the Coffee Gets Cold',
    author: 'Toshikazu Kawaguchi',
    totalPages: 224,
    startDate: '2026-09-01',
    finishDate: '2026-09-20',
    elapsedDays: 20,
    ppd: 11.2,
    archetypeId: 'bedtime-taster',
    rating: 4.2,
    review:
      'Read 10-15 pages each night with a cup of chamomile tea. Melancholy yet deeply comforting café time travel.',
    genre: 'Fantasy',
    format: 'Physical',
    coverUrl: 'https://covers.openlibrary.org/b/id/10189912-M.jpg',
    isbn: '9781335430991',
    publisher: 'Hanover Square Press',
    celebrationMessage:
      'Sanctuary achieved. Gently tasting 11.2 pages a night across 20 evenings is the gold standard of restorative reading. You chose peace over speed, turning this book into a nightly cup of comfort.',
    createdAt: Date.now() - 200000,
  },
];
